### ISSUE TITLE
关于表情框（smilies-body）

### ISSUE THREAD

**Issue by SpringYeh** [ihoey/Hitalk#5]
已按照步骤将一切弄好，appId, appKey以及 Hitalk.js 里的https://hitalk.dode.top 都换成了自己的，表情包用的还是原 cdn.dode.top/newpaopao|alu，其他的都没改，也没报错了。但是表情框（\<div class=\"smilies-body\">\</div>）内部是空的，不知为何

**Comment by ihoey** [comment]
有在线的地址么 我给你看下 这样描述看不出来问题在哪里呢

**Comment by SpringYeh** [comment]
URL: https://easter.cinzano.xyz
又出现了新的问题，看首页第一篇文章评论，我发了一条之后，表情包主体就能出现了，但是控制台就又多了一个报错（Uncaught (in promise) TypeError: Cannot read property 'classList' of undefined）；其他没有任何评论的文章，控制台无此错误，但是表情按钮按了没反应，只有发一条评论后才会触发您在Hitalk.js中写的表情包逻辑。

**Comment by SpringYeh** [comment]
把工程源码搞到本地调试了，之前那个不算大bug，单页评论容量pageSize=10时，评论数小于10就会报那个错误。现在发现新bug：如pageSize=10；当评论数有13条时，应该有两页，正常情况下方索引应是Page 1、Page 2、Page Next；而现在的情况是缺了那个2和next按钮，从而导致最后一页评论无法加载出来。比如博主文章‘解决 ubuntu 服务器中文乱码’这篇的评论区也是如此。

**Comment by ihoey** [comment]
感谢  我修复下这个bug

**Comment by ihoey** [comment]
已经修复这个问题两个问题了 非常感谢你
